### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by merzoukfatima** [202306-NEA-DZ-FEW/Capstone-Dream-Team#1]
**Task title**
Home Page

**Task description**
Create a Home Page and Its Components. This is where users can get an overview of your service, and it can include links to other important pages.

**Subtasks**
- Navbar #8 
- Hero Section
   - [x] #48 
        - [x] Picture
        - [x] Text
        - [x] Button (Donate!)
 
 - Instruction Section
     - [x] Instruction Step Card
     - [x] Picture
     - [x] Text

- Goals Section
  - [x] Goal Card
  - [x] Picture
  - [x] Text
- Sponsors Section
     - [x] Logo Card
     - [x] Picture
     - [x] Name
- Blogs Section 
   - [x] Blog Card
       - [x] Picture
       - [x] Title
       - [x] Description
       - [x] Date
       - [x] Readers Number
       - [x] Comments Icon
       - [x] Button (Read More) 
- Join Us Section
   - [x] Hero Card
       - [x] Picture
       - [x] Text
       - [x] Button (Buy a Meal Now!)
 
- Footer #9 

**Link to the component on Figma**
[Home page]https://www.figma.com/file/sDlEio3FtEwhvkQQyYJUZS/share-and-care?type=design&node-id=1-164&mode=design&t=PEV1PhH2F1MLKJx8-4

**Comment by ikoworld** [comment]
homepage is done
