### ISSUE TITLE
Cart Page

### ISSUE THREAD

**Issue by merzoukfatima** [202306-NEA-DZ-FEW/Capstone-Dream-Team#11]
**Issue Title**
Cart Page

**Issue Description**
Create a Cart Page to manage meal orders with the following components

**Subtasks**

- [ ] Display Selected Meal Items
  - [ ] Show Meal Names
  - [ ] Allow Quantity Selection
  - [ ] Calculate Subtotal per Meal

- [ ] Total Amount Display
  - [ ] Calculate and Display the Total Amount for the Selected Meals

- [ ] Checkout Button
  - [ ] Implement a Checkout Button for Proceeding with the Meal Orders

**Screenshots**
(Include relevant screenshots if available)

**Link to the Component on Figma**
(Insert the link to the design on Figma if applicable)
