### ISSUE TITLE
Article Page

### ISSUE THREAD

**Issue by merzoukfatima** [202306-NEA-DZ-FEW/Capstone-Dream-Team#14]
**Issue Title**
Article Page

**Issue Description**
Create an Article Page with Similar Articles/Recommendations

**Subtasks**

- [x] #34
- [x] **Similar Articles/Recommendations Section:** #49 
   - [x] Display a list of similar articles or recommendations.
   - [x] Each article card should include:
     - [x] Title.
     - [x] Author's Name.
     - [x] Excerpt or Summary.
     - [x] "Read More" Button.

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/Capstone-Dream-Team/assets/104175862/e74e3b67-c51e-42b2-9f85-8207a766f32c)

**Link to the Component on Figma**
(Insert the link to the design on Figma if applicable)
