### ISSUE TITLE
Admin dashboard Page

### ISSUE THREAD

**Issue by merzoukfatima** [202306-NEA-DZ-FEW/Capstone-Dream-Team#3]
**Issue Title**
Admin Dashboard Page

**Issue Description**
Create an Admin Dashboard Page and its Components

**Subtasks**

- [x] Implement Admin Login functionality.
- [x] #15
    - [x] #22
        - [x] Display a list of purchases.
            - [x] Include User ID, User Name, Date, Meal ID, Meal State.
    - [x] #20
        - [x] Add new meals.
        - [x] Implement meal editing functionality:
            - [x] Edit Meal Picture.
            - [x] Edit Meal Description.
            - [x] Edit Meal Quantity.
        - [x] Archive a Meal by ID.
    - [x] #21
        - [x] Display Statistics.
        - [x] Show the count of active meals.
    - [x] #56
        - [x] Edit Email.
        - [x] Edit Password.
        - [x] Edit Name.
        - [x] Add Logo.
        - [x] Edit Active Meal Capacity.
    - [x] Log Out

**Screenshots**
(Include relevant screenshots if available)

**Link to the Component on Figma**
(Insert the link to the design on Figma if applicable)
