### ISSUE TITLE
Meals Page

### ISSUE THREAD

**Issue by mouloud247** [202306-NEA-DZ-FEW/Capstone-Dream-Team#4]
**Issue Title**
Meals Page

**Issue Description**
Create a Meals Page with Restaurants and Meals Display

**Subtasks**

1. **Header Section:**
   - [x] Display Title: "Explore Restaurants and Meals"
   - [x] Include an optional search bar for filtering restaurants or meals.

2. **List of Restaurants:**
   - [x] Display restaurants as cards or tiles.
   - [x] Each restaurant card should include:
     - [x] Restaurant Picture/Logo
     - [x] Restaurant Name
     - [x] Restaurant Description (optional)
     - [x] "View Meals" Button

3. **List of Meals for Selected Restaurant:**
   - [x] Implement the functionality that appears in a section or navigates to a new page when a user clicks the "View Meals" button on a restaurant card.
   - [x] Display meals as cards or a list.
   - [x] Each meal card should include:
     - [x] Meal Name
     - [x] Meal Description
     - [x] Meal Price
     - [x] "Add to Cart" Button

**Screenshots**
(Include relevant screenshots if available)

**Link to the Component on Figma**
(Insert the link to the design on Figma if applicable)
