### ISSUE TITLE
Integrate Firebase

### ISSUE THREAD

**Issue by merzoukfatima** [202306-NEA-DZ-FEW/Capstone-Dream-Team#6]
**Task title**
Integrate Firebase

**Task description**
 Install Firebase and associated functionality

**Subtasks**
- [x] Create Firebase Project
- [x] Add Firebase to the repo in the util folder
- [x] Hide API Key
